### ISSUE TITLE
Error when saving / using files for the test code phat_small

### ISSUE THREAD

**Issue by LanaEid** [BEAST-Fitting/beast-examples#3] opened 2020-01-17 22:43 UTC
Issue when running the following:
python beast/plotting/plot_indiv_fit.py beast_example_phat/beast_example_phat
(from this: https://beast.readthedocs.io/en/latest/example.html )

Error message:
python: can't open file 'beast/plotting/plot_indiv_fit.py': [Errno 2] No such file or directory

The files are there and readable, so perhaps it is an issue of where they are saved on my computer.

**Comment by jwuphysics** [comment] 2020-01-21 19:15
I'm guessing that it can't find the plotting script. There used to be a symbolic link to the `beast/` parent directory, but since it's no longer there and the `beast-examples` repository might be saved elsewhere, the original relative path (`beast/plotting/plot_indiv_fit.py`) probably won't work anymore. 

In my case it looks more like
```
python ../../beast/beast/plotting/plot_indiv_fit.py beast_example_phat/beast_example_phat
```

**Comment by karllark** [comment] 2020-01-21 21:10
Yeah, this is the problem.  There might be a way to do this calling this as a module, but not sure.  Need to investigate.  For now, explicitly calling the script as @jwuphysics says above should work.

**Comment by karllark** [comment] 2020-01-21 21:13
Really need to get this script integrated into the entry-points way of calling.  See https://github.com/BEAST-Fitting/beast/blob/master/beast/main.py

But I remember code changes will be needed in plot_indiv_fit.py to get this to work.

**Comment by LanaEid** [comment] 2020-01-22 04:10
I have attached three images for reference, in this order:
1 - What I thought was a successful test run of phat_small is shown in this image.  
2 - Using your suggestions, I got the following error messages, so I decided to check different directories to see if the files are really there.  
3 - This is another directory check to see if the files are there.  

I cannot figure out what could be going wrong, but hopefully someone here can.  I appreciate the suggestions!  

![hopefully_successful_run_of_phat_small_and_where_things_are_saved](https://user-images.githubusercontent.com/43757615/72864627-b3f88a80-3ca2-11ea-986c-9f93d4a1eda3.png)
![tried_to_show_plots_and_info_using_your_suggestions__and_error_messages__showing_ls_in_one_location_for_reference](https://user-images.githubusercontent.com/43757615/72864634-b78c1180-3ca2-11ea-85f8-a83b08735c9c.png)
![showing_ls_in_other_location_for_reference](https://user-images.githubusercontent.com/43757615/72864645-bce95c00-3ca2-11ea-8f34-d6498178b0ed.png)

**Comment by karllark** [comment] 2020-01-22 13:06
The issue is that there are parts of the BEAST run that fail if some of the intermediate files exist from previous runs.  In this case, it is the `seds_trim.grid.hd5` files.  The solution is to remove the offending files.  As it can be a number of different files, I usually just delete the entire `beast_example_phat` directory anytime I get this error.  Then all the files are recreated.  

Clearly this is not ideal and the code should check if there is a file and delete it if that is what is needed.  I'll open an issue on the beast to put this on the list of things to fix.

**Comment by LanaEid** [comment] 2020-01-22 19:30
I tried deleting every file in the beast_example_phat directory and running it again, and I (still) got the following:

![still_did_not_work](https://user-images.githubusercontent.com/43757615/72927053-87388780-3d23-11ea-8788-5d7fb9b63e8c.png)

I am going to try deleting / uninstalling everything and trying again.

**Comment by jwuphysics** [comment] 2020-01-22 19:55
It looks like you ran the last command in your home directory, i.e., `~` which is equivalent to `/home/lanaeid`, so my guess is that the relative file path still didn't work. In your case, where I assume your directory structure looks something like:

```
~
├── beast
│   ├── beast
│   │   ├── plotting
│   │   └── (...)
│   └── (other stuff)
├── beast-examples
│   └── phat_small
└── (more stuff)
```

So if you're in `~` directory, then you'll want to run something like:

```python ~/beast/beast/plotting/plot_indiv_fit.py ~/beast-examples/phat_small/beast_example_phat/beast_example_phat```

Or, as another example, say you're in the directory `~/beast-examples/phat_small`. Then you could run it like 

```python ~/beast/beast/plotting/plot_indiv_fit.py beast_example_phat/beast_example_phat```

**Comment by karllark** [comment] 2020-01-22 20:13
To be clear, when I suggested deleting everything it was so that you could `run_beast.py -potf` again.  After that, you should have the appropriate files to `plot_indiv_fit.py`.  I have a feeling I am giving the incorrect advice - apologies.

**Comment by karllark** [comment] 2020-01-22 20:14
Follow @jwuphysics advice.

**Comment by LanaEid** [comment] 2020-01-22 20:15
Okay, I will try that - no problem!

**Comment by LanaEid** [comment] 2020-01-22 20:33
This is what I inputted/got:

![error_output](https://user-images.githubusercontent.com/43757615/72931638-3e390100-3d2c-11ea-90e9-61e83b4cbc9c.png)

I am not sure at this point if it is an issue with the code or with the fact that I am running this all in an Ubuntu Terminal that I installed on Windows 10.  Perhaps it is an unable to deal with with displaying things?  In that case, I can try using a virtual machine and seeing if that works better.

**Comment by jwuphysics** [comment] 2020-01-22 20:44
That is the same output that I normally get, so it looks like this is working! Except the window manager probably doesn't know how to display the plot output. I wonder if it's related to [this issue](https://stackoverflow.com/questions/43397162/show-matplotlib-plots-in-ubuntu-windows-subsystem-for-linux)...

If so, you may need to install `VcXsrv` and `python-tk` and then run `export DISPLAY=localhost:0.0` in the terminal before the python command. Overall, though, it looks like your example is able to run!

**Comment by LanaEid** [comment] 2020-01-23 02:35
![Figure 1](https://user-images.githubusercontent.com/43757615/72952087-d18b2a00-3d5e-11ea-8d9c-329e992f5e78.png)

It worked!!  It displayed all the plots and data!!  Thank you very much for your assistance, patience, and explanations.

**Comment by karllark** [comment] 2020-01-23 13:16
Yeah.  Closing the issue then.

**Closed as completed by karllark** 2020-01-23 13:16 UTC
